### ISSUE TITLE
Party cast bars

### ISSUE THREAD

**Issue by lwznrx** [wotlk-addons/Overhead#1]
Atm the addons hides completely party nameplates at line 227, because they aren't registered in the function. I tried to change it (before it looped from 1 to bracket, and party1/2 weren't in the uids) but it didn't work. Testing stuff requires to be in arena, so cba changing it atm.
A simple temporary way to show party nameplates is to change the UpdateArt function, removing the HideArt stuff. (line 257)

**Comment by vendethiel** [comment]
18600dfd9eb807b8fe35b623b12c5535a6e25ebb
